### ISSUE TITLE
[v6] MCU_*

### ISSUE THREAD

**Issue by chschlue** [KiCad/kicad-symbols#3059]
- [ ] add alternate pin types

**Comment by myfreescalewebpage** [comment]
@KiCad/librarians not sure, but I think alternate pin type definition need first to go on v6, isn't it ?

**Comment by chschlue** [comment]
Yes.

**Comment by myfreescalewebpage** [comment]
Probably the best way to handle MCU is to script them. I mean, if it is possible, one script for all manufacturers. Will be easier to ensure the largest consistency across the lib.

Will try to think about that

**Comment by chschlue** [comment]
We have the [STM32 generator](https://github.com/KiCad/kicad-library-utils/tree/master/schlib/autogen/stm32)
Perhaps that can serve as a starting point.

**Comment by cpresser** [comment]
One feature I would love is drop-in compatible symbols for parts of the same series. An example for that is here: https://github.com/KiCad/kicad-symbols/pull/2336

**Comment by myfreescalewebpage** [comment]
@chschlue yes I know the STM32 generator, but it is based on the usage of (xml?) file from STM workbench (as far as I know). Which is not useful for the other manufacturers

**Comment by cpresser** [comment]
I am pretty sure we need to devise our own format. 
* The STM `.xml` files need to be converted to it. 
* Microchip provide `bxl` files that might have some information. https://github.com/KiCad/kicad-symbols/issues/2098
* For quite a lot of manufacturers we might need to manually write those files.
* Perhaps we can add a workflow for `*.BDSL` files
* At least some information needs to be  added manually anyway (GNDStacks, Layout).
* We could also use that generator for other parts. `FPGA_*` comes to mind.

WIP yaml format. 
* This is just a rough sketch!
* The idea of `group` is that all parts in one group share the same layout. The script looks at all parts, merges their pin-groups to find the common pins, then skips the pins that are not part of the specific symbol.
* the multiple-pin-functions feature of v6 is modeled in this proposed `.yaml` format. 
* Aliases with different footprints could also be added, but right now I have no clue how that works

```yaml
group: SAMD21
  name: ATSAMD21E18A
  description: foo
  keywords: bar
  aliases:
    ATSAMD21E17A:
      - description: foo2
      - keywords: bar17
  footprint: gnorfrogl
  footprint-filters:
   - abc
   - def
  pingroups:
    portA:
      position: right
      pins:
        # pin numbers as keys, since they are unique
        14:
          # list of functions 
          - PA14: Bidir
          - AN0: Input
          - TMR0OUT: Output
        15:
          - PA15: Bidir
          - AN1: Input
          - SERCOM2[0]: Bidir
    portB:
      pins:
        32:
          - PA02: Bidir
  supply:
    # we need GND stacks and stuff, so a different format for supply pins
    - GND:
      # on explicit position for GND, some heuristic can take care of that.
      - pins:
        - 7
        - 22
        - 41
    - GNDANA: 26
    # placing of those
    - VDDCORE:
      - position: top 
      - pins: 27 # just the number of the pin, pinlist if multiple pins
```
